### ISSUE TITLE
Ignore some errors

### ISSUE THREAD

**Issue by kevinburke** [kevinburke/multi-emailer#1]
When sending out emails, we occasionally see this error, with no more information:

```
"googleapi: Error 500: Backend Error, backendError"
```

It's not clear that we should try that request again, as the request may have succeeded we don't want to spam people with emails. But maybe we should stagger sending a little bit.

We could also limit the number of concurrent sends in flight at once across the entire app.

**Comment by skylartaylor** [comment]
Do we think that this is some sort of rate-limiting issue? Also, in what universe does Google not provide more information than that on an error...

**Comment by kevinburke** [comment]
It's not really clear, unfortunately. This suggests it's retryable, maybe we could try to trigger it and see whether the message gets resent. https://developers.google.com/drive/v3/web/handle-errors
