### ISSUE TITLE
Provide welcome screen before redirecting people to Google

### ISSUE THREAD

**Issue by kevinburke** [kevinburke/multi-emailer#3]
We ask for people's email addresses, which can be pretty sensitive. It would be good to explain how we use it (we can't see your inbox, for example, we can only send mail).

**Comment by skylartaylor** [comment]
This is probably the first thing I'm going to attempt to tackle. Asking for Gmail auth as the first thing we do is pretty poor UX.

**Comment by kevinburke** [comment]
We are going to want to provide a value for ServeLogin here: https://godoc.org/github.com/kevinburke/google-oauth-handler#Config

The default is just to do a 302 redirect: https://github.com/kevinburke/google-oauth-handler/blob/master/lib.go#L128-L130

**Comment by kevinburke** [comment]
@jmhodges pointed out that this would also give the tool better SEO.
